[libraries]

acc.files = [
"tfe4141_rsa_integration_kit_2024\\RSA_accelerator\\testbench\\rsa_accelerator_tb.vhd",
"tfe4141_rsa_integration_kit_2024\\RSA_accelerator\\source\\rsa_regio.vhd",
"tfe4141_rsa_integration_kit_2024\\RSA_accelerator\\source\\rsa_msgout.vhd",
"tfe4141_rsa_integration_kit_2024\\RSA_accelerator\\source\\rsa_msgin.vhd",
"tfe4141_rsa_integration_kit_2024\\RSA_accelerator\\source\\rsa_core.vhd",
"tfe4141_rsa_integration_kit_2024\\RSA_accelerator\\source\\rsa_accelerator.vhd",
"tfe4141_rsa_integration_kit_2024\\RSA_accelerator\\IP\\src\\exponentiation.vhd",
]

soc.files = [
"tfe4141_rsa_integration_kit_2024\\RSA_soc\\source\\rsa_soc.vhd",
]


lib.files = [
"tfe4141_rsa_integration_kit_2024\\Exponentiation\\testbench\\*.vhd",
"tfe4141_rsa_integration_kit_2024\\Exponentiation\\source\\*.vhd",
]

UNISIM.files = [
  'C:\Xilinx\Vivado\2024.1\data\vhdl\src\unisims\unisim_VCOMP.vhd',
]
UNISIM.is_third_party = true

[lint]
unnecessary_work_library = false # Disable linting for the 'library work;' statement